### ISSUE TITLE
Error: Expected linebreaks to be 'LF' but found 'CRLF'

### ISSUE THREAD

**Issue by FrozenFury** [mldangelo/personal-site#263]
When running "npm start" I get a bunch of these errors. Do you know what might be causing this?

**Comment by mldangelo** [comment]
Are; you on Windows? So far, I have only tested my site on Ubuntu and macOS. @kuripart recently submitted and then closed a PR related to this: https://github.com/mldangelo/personal-site/pull/260 Please take a look at his configuration changes and the comment I left in that thread. I'll leave this issue open until your problem is resolved and I make configuration changes and/or improve documentation for Windows developers (hopefully tomorrow).

**Comment by FrozenFury** [comment]
Yup, Windows. This, in combination with disabling some other eslint features fixed the issue.

**Comment by mldangelo** [comment]
Glad you were able to resolve the issue. If you don't mind sharing your changes to your eslint config, I can work to integrate them into this repo for other windows users.

**Comment by FrozenFury** [comment]
Of course, I'll send them when I get home.

**Comment by FrozenFury** [comment]
I believe this config in `.eslintrc` is what allowed me to avoid the errors:

```    
"jsx-a11y/anchor-is-valid": ["error", {
      "components": ["Link"],
      "specialLink": ["to", "hrefLeft", "hrefRight"],
      "aspects": ["noHref", "invalidHref", "preferButton"],
      "linebreak-style": 0,
      "global-require": 0,
      "eslint linebreak-style": [0, "error", "windows"]
    }],
```

**Comment by mldangelo** [comment]
Thanks @FrozenFury

**Comment by pravinmobilefirst9** [comment]
Run this in your terminal or cmd prompt

git config core.autocrlf false
git rm --cached -r .
git reset --hard

This usually happens when the project is created on UNIX based system & then used on a windows system because both have different line endings.

We need to disable auto CRLF on git & uncommit & recommit changes.
