### ISSUE TITLE
Please help me deploying this on github 

### ISSUE THREAD

**Issue by DhruvDoshi** [mldangelo/personal-site#281]
I tried everything from versal to netify along with heroku but nothing worked

**Comment by rayliuca** [comment]
If you have modified the package.json file already and is using git with your password and all that, just run `npm run deploy` at the root of the repo folder. This will build and deploy the static page to the gh-pages branch, then you need to go to the repo setting -> page -> source and change the branch to gh-pages.

**Comment by notrueblood** [comment]
Closing this as I believe @rayliuca's solution solves the issue. The key is that we're deploying using github pages, rather than versal/netify/heroku. The deployment steps in the project's root readme should lead to a successful deployment if followed. I'll revisit the steps and try to improve clarity or add any missing steps
